import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>EtherCast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='body1 font-poppins'>
            <div id="home-container" className='font-poppins'>
            
                <div id="inner">
                
                    <h1 className='head text-4xl tracking-[8px] font-poppins font-bold'><span className='text-5xl'>E</span>ther<span className='text-5xl'>C</span>ast</h1>
                    <p className="subtitle font-poppins">A Blockchain based E-Voting System</p>
                    <Link href='/Login' className="cta cta--white ig font-poppins text-center items-center text-lg px-12 py-2 w-[200px] h-[50px]">Login</Link>
                    <Link href='#' className="cta cta--white ig font-poppins text-lg text-center items-center px-12 py-2 w-[200px] h-[50px]">Guest User</Link>
                </div>

                <div id="illustration">
                    
                    <div id="dash" className="crypto-icons"><i className="fa-brands fa-ethereum"></i></div>
                    <Image src={'./miota.svg'} alt={'iota img'} id='iota' className= "crypto-icons" height={100} width={100} />
                    <Image src={'/eth.svg'} alt={'eth img'} id='eth'className="crypto-icons" height={100} width={100} />
                    <Image src={'/monitor.svg'} alt={'monitor img'} id='monitor' height={400} width={450} />
                </div>
            </div>
        </div>
        
    </>
  )
}
