import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
// import styles1 from '../styles/'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>EtherCast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='body1'>
            <div id="home-container">
            
                <div id="inner">
                
                    <h1>EtherCast</h1>
                    <p className="subtitle">A Block-chain Based E-voting System</p>
                    <Link href='/regi' className="cta cta--white ig" >Login</Link>
                    {/* <a href="/regi" className="cta cta--white ig" >Login</a> */}
                    <Link href='#' className="cta cta--white ig" >Guest User</Link>
                    {/* <a href="#" className="cta cta--white ">Guest User</a> */}
                </div>

                <div id="illustration">
                    
                    <div id="dash" className="crypto-icons"><i className="fa-brands fa-ethereum"></i></div>
                    <Image src={'./miota.svg'} alt={'iota img'} id='iota' className= "crypto-icons" height={100} width={100} />
                    <Image src={'/eth.svg'} alt={'eth img'} id='eth'className="crypto-icons" height={100} width={100} />
                    <Image src={'/monitor.svg'} alt={'monitor img'} id='monitor' height={400} width={450} />
                </div>
            </div>
        </div>
        
    </>
  )
}
